"""add remoteuser

Revision ID: 5c6d07e2a9c1
Revises: 1487ea15dcb8
Create Date: 2022-02-13 01:54:01.310088

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5c6d07e2a9c1'
down_revision = '1487ea15dcb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remoteuser',
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('inbox', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remoteuser')
    # ### end Alembic commands ###
